### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#102]
Right now rhai is not really supported in any editor and even if the amount of custom syntax makes me want to define my own syntax highlighting anyways.

The following editors will be having an official plugin:

* Visual Studio Code
* Vim/Neovim

If anyone wants another editor please tell me now, I might consider adding your proposed editor to the list.

~~I want to [decide on a new name](https://github.com/TimUntersberger/wwm/issues/100) before I start working on this.~~

~~I will also move this repo into its own organization, which will also contain the plugins.~~

**Comment by TimUntersberger** [comment]
I implemented this a bit for vim in my own config which you can find [here](https://github.com/TimUntersberger/neovim.config)

**Comment by cristianovitorino** [comment]
There is [Rhai Language Support](https://marketplace.visualstudio.com/items?itemName=Aster.vscode-rhai) for Visual Studio Code. I'm currently using it an it's working pretty well.

**Comment by TimUntersberger** [comment]
Created a syntax highlighting plugin for the upcoming new language. [Nogscript Language Support](https://marketplace.visualstudio.com/items?itemName=TimUntersberger.nogscript-language-support)
