### ISSUE TITLE
Display current focused window title in bar

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#104]
Somehow make it possible to show the currently focused window title in the bar.

**Comment by keepitsane** [comment]
Do you think that having a colored border around the currently focus window, would be better to quickly show which window is in focus. Maybe when the user is switching focus a border shows up and follows the movement of focus and then after a few seconds it fades away. If the user then wants to quickly tell which window has focus they can hold down ALT (or some shortcut) and have some time threshold that once reached it will bring back the border highlight for the current focused window until ALT is let go.

**Comment by TimUntersberger** [comment]
This feature isn't really for showing the currently focused tile, but just a nice to have.

Do you sometimes lose where you are? (I never really have that problem)

I think its best to open a seperate issue for this, if you need it.
