### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#110]
It would be nice if we could show the user a notification when something goes wrong.

We would have to create our own notification window, because you need to be a verified program to send Windows 10 notifications.

A custom window will also give us a lot more flexibility.

Also provide a notifications library for scripting purposes under `nog/popups`

**Comment by ramirezmike** [comment]
This could be a way to resolve #87 Just handle the panic and show a notification saying wwm can't manage that window.

**Comment by TimUntersberger** [comment]
First demo is live in the `popups` branch and the corresponding release `popups-release`.

**Comment by TimUntersberger** [comment]
The executable just shows a popup and does nothing else

**Comment by TimUntersberger** [comment]
I played around with this idea a bit more and you can now create a new popup in the config.

```nog
popup_new("Test window", 140, 60, #{
    text: ["Hello World"],
    padding: 20
});
```

I am still not happy with the API, but this is very WIP.

![image](https://user-images.githubusercontent.com/32014449/90320327-92ae0300-df40-11ea-9176-a1d74b6614dc.png)
