### ISSUE TITLE
Full screen video should cover app bar

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#116]
When watching videos and it is played in full screen, would it be possible to hide the app bar. I have a toggle config set for the app bar when I am watching full screen video, but that disables the app bar on all my monitors rather than just the one monitor I am watching the video on. Maybe a setting can be added to the rules for example for programs like VLC and Firefox that can exist above the app bar, so when it goes to full screen mode it will be entirely above the app bar.

**Comment by TimUntersberger** [comment]
The appbar is currently set to `topmost`, which has the same effect like when you set `always on top` in the task manager. Do you think we could just have the appbar be a normal window?

**Comment by keepitsane** [comment]
How does the task bar work is that set to topmost? Cause the task bar gets hidden when an application goes full screen, so I think emulating the default behavior of the task bar might be the best.

**Comment by TimUntersberger** [comment]
> How does the task bar work is that set to topmost? Cause the task bar gets hidden when an application goes full screen, so I think emulating the default behavior of the task bar might be the best.

The taskbar hides when a window would cover it. 

The bar is set to be the topmost window to always know whats going on. I tried to no longer have it be the topmost window, but this is slightly awkward when you have a maximized window that is not managed (it completely hides the bar). I can't find out how I can detect when a video goes fullscreen, as each applications can do it differently.

**Comment by keepitsane** [comment]
Sorry for the delayed response.

In my search I found this maybe it could help [https://docs.microsoft.com/en-us/previous-versions//bb776821(v=vs.85)?redirectedfrom=MSDN#processing-appbar-notification-messages](https://docs.microsoft.com/en-us/previous-versions//bb776821(v=vs.85)?redirectedfrom=MSDN#processing-appbar-notification-messages)

I am not entirely sure if in your code you are using the appbar functionality that the API provides, but perhaps if you are not switching to an appbar could potential help simplify the logic.

**Comment by TimUntersberger** [comment]
> In my search I found this maybe it could help https://docs.microsoft.com/en-us/previous-versions//bb776821(v=vs.85)?redirectedfrom=MSDN#processing-appbar-notification-messages

Nice find! I will try an experimental rewrite of the bar to use the appbar api.
