### ISSUE TITLE
Workspace id not displayed on secondary monitors

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#127]
In a multi monitor setup the workspace id only show up for numbers that are not assigned to a monitor. In my config I have workspace id 4 to 6 set to one of my secondary monitor and the workspace show up on the correct monitor, but the id does not display in the bar. For workspace 1-3 and 10 I don't have then assigned to a specific monitor and their numbers show up properly in the bar on my primary monitor.

**Comment by TimUntersberger** [comment]
> In a multi monitor setup the workspace id only show up for numbers that are not assigned to a monitor

How are the workspaces created? Do you open a window that is assigned to that workspace or do you switch to the workspace?

**Comment by keepitsane** [comment]
I figured out the issue. When assigning a workspace to a specific monitor in the config file you must provide a text value otherwise nothing is displayed. Maybe the default should be if not text value is put it will just display the workspace id as the text. If a person really did want to have no workspace id displayed they can set `text: ""`

So right now if you want the workspace id to show up you must set it like the following:
```
workspace 4 #{
  monitor: 1,
  text: " 4 "
};
```

**Comment by TimUntersberger** [comment]
> Maybe the default should be if not text value is put it will just display the workspace id as the text

That is actually how it *should* work right now. Good job!
