### ISSUE TITLE
Using workspace id 10 cause the bar to break

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#128]
The workspace id 10 does not disappear if not windows are being managed on that id and  when switching back to an id 1-9 the workspace highlight becomes resized and does not go back to the original size unless nog is reloaded.

![Screenshot 2020-08-13 101440](https://user-images.githubusercontent.com/13246774/90145899-6cc10c80-dd4e-11ea-9f0b-ec6f4261d7f5.png)

![Screenshot 2020-08-13 101454](https://user-images.githubusercontent.com/13246774/90145903-6df23980-dd4e-11ea-937e-1dd05aeb12c5.png)

Having workspace 10 open and switching to a different workspace on the same monitor that has not windows being managed glitches out the and makes duplicated workspace ids in the bar.

![Screenshot 2020-08-13 101338](https://user-images.githubusercontent.com/13246774/90145878-692d8580-dd4e-11ea-922d-299954440e16.png)

![Screenshot 2020-08-13 101402](https://user-images.githubusercontent.com/13246774/90145891-6b8fdf80-dd4e-11ea-9195-69d41024797b.png)

**Comment by TimUntersberger** [comment]
Which branch are you using? I can't reproduce this. Did you use the latest development exe?

**Comment by keepitsane** [comment]
I just downloaded the last development exe you published. Here is how I can reproduce the issue when I have nog launched fresh switching from id 1 straight to 10 and back the container readjust correctly. But if I got from 1 to 4, which is assigned to one of my secondary monitors and then back to 10 is when it breaks.

This screenshot shows when I have workspace 4 in focus the bar on my primary displays this when a workspace on a different monitor is selected.

![Screenshot 2020-08-13 103739](https://user-images.githubusercontent.com/13246774/90148316-35a02a80-dd51-11ea-95a2-ce03fd4e4005.png)

**Comment by keepitsane** [comment]
Looks like even when not using workspace 10 some glitches popup. If you go to a workspace for example id 3 open a few apps and then close all of them so not windows are being managed on that workspace and switch back to a different workspace previously workspaces with no managed windows on them would disappear from the bar. This no long happens and causes this duplicate glitch.

![image](https://user-images.githubusercontent.com/13246774/90150692-edced280-dd53-11ea-81e6-6bc7c4eed9bb.png)

**Comment by keepitsane** [comment]
Here is another example just to help you further.

Currently workspace 4 is focused and 5 and 6 have windows that are being managed by nog:
![image](https://user-images.githubusercontent.com/13246774/90151271-882f1600-dd54-11ea-8925-18963b1a8304.png)

Switching to workspace 5 does this:
![image](https://user-images.githubusercontent.com/13246774/90151369-a5fc7b00-dd54-11ea-8da4-bb0c2ff85dc0.png)

**Comment by TimUntersberger** [comment]
The latest `development` build contains an attempt at fixing this.

**Comment by keepitsane** [comment]
Everything seems to be working smoothly now. I will close this issue at the end of day.
