### ISSUE TITLE
Include version number for development builds

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#129]
Would help when creating bug reports and you can make the version number be displayed when you right click nog in the notification area. Maybe for development builds just display the commit id.

![Screenshot 2020-08-13 104327](https://user-images.githubusercontent.com/13246774/90149002-fc1bef00-dd51-11ea-8a91-dd8725bfd156.png)

**Comment by TimUntersberger** [comment]
When you now hover over the icon the system tray you can see which branch and commit you are using. A release with a tag will just have the tag number.
