### ISSUE TITLE
How to setup a rule for an application that has a dynamic title

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#130]
I haven't always got the rule feature to work when assigning an application to a specific workspace. For example, I have nog ignore file explorer and it works when I open a fresh window. But if I open a specific folder using the command line or opening the download location from firefox the title bar of the file explorer is different and nog will manage it. 

Any suggestions on how to get around this?

**Comment by TimUntersberger** [comment]
I don't think that is possible right now. What could be a possible solution is also matching on the process name. 

You could then write "explorer.exe", because the process name almost never changes.

**Comment by TimUntersberger** [comment]
I now have the full executable name like this: `C:\\Windows\\explorer.exe`

I am not sure whether to create a seperate keyword `process_rule` that uses the process name instead of the window name to avoid false positives.

Also should we use the full path or just the executable? Using just the executable name could actually also cause false positives, if two applications have the same name, but if you move the executable the rule won't match anymore. What are your thoughts on this?

**Comment by keepitsane** [comment]
Is there any reason to not just allow both to be valid?

**Comment by TimUntersberger** [comment]
> Does the using the executable name work in the current development build? If yes how would I list that in my config file I can't seem to be nog to working with executable name or full path.

I haven't pushed it yet, because I am still thinking about how to go about this.

> Is there any reason to not just allow both to be valid?

No haha.

I am thinking about having the following api

```nog
process_rule "<process_name>" #{
  // additional path property to narrow down the rule
  // everything that rule has
};
```

### Example
```nog
process_rule "explorer.exe" #{
  manage: false
};
```
or
```nog
process_rule "explorer.exe" #{
  path: "C:\\Windows",
  manage: false
};
```
or
```nog
ignore_process "explorer.exe";
```

**Comment by keepitsane** [comment]
I like this. In the second example would it be better to just remove the path option and make it something like this:
```
process_rule "C:\\Windows\\explorer.exe" #{
  manage: false
};
```
It would just simplify it a bit or does that add some additional complexities that I am missing?

**Comment by TimUntersberger** [comment]
Maybe it be even possible to check if the string contains a `\\` to know when you want to just check the process name and when the full path.

**Comment by TimUntersberger** [comment]
So

```nog
process_rule "explorer.exe" #{
  manage: false
};
```

just checks the executable name and

```nog
process_rule "C:\\Windows\\explorer.exe" #{
  manage: false
};
```

checks the whole path

**Comment by keepitsane** [comment]
Yeah I think that would be the best imo

**Comment by TimUntersberger** [comment]
Actually I no longer feel like having a new keyword is the right choice (the shortcut will still be introduced). This will introduce a lot of duplication.

I am thinking about just having a flag called `process`.

Example

```nog
rule "explorer.exe" #{
  process: true,
  manage: false
};
```
or 
```nog
ignore_process "explorer.exe";
```

**Comment by keepitsane** [comment]
Just thinking about this wouldn't most peoples first thought to create a rule be to do it with a path or executable rather than regex? So maybe make executable/path the default assumption, with a flag to switch to `regex`. 

Just an idea

**Comment by TimUntersberger** [comment]
The string is still a regex, but I think you mean to change the default from matching the window title to the process name?

**Comment by TimUntersberger** [comment]
I agree with you.

**Comment by TimUntersberger** [comment]
This is now pushed to `development`.

This is what my `rules.nog` now looks like
```nog
ignore "explorer.exe";
ignore "Taskmgr.exe";
ignore "SnippingTool.exe";

rule "firefox.exe" #{
    has_custom_titlebar: true,
    workspace_id: 2,
    firefox: true
};

rule "Discord.exe" #{
    has_custom_titlebar: true
};

rule "Spotify.exe" #{
    has_custom_titlebar: true
};

rule "chrome.exe" #{
    has_custom_titlebar: true,
    workspace_id: 2,
    chromium: true
};

rule "Code.exe" #{
    has_custom_titlebar: true
};
```

**Comment by keepitsane** [comment]
Nice I am liking this version a lot and make setting rules much simpler. One bug I noticed I can open another issue if you would like me to is with Task Manager. When I open task manager now it is unmanaged since I have Nog ignore it using `ignore "Taskmgr.exe";`, but for some reason a blank tile opens up in the workspace that is currently in focus. This didn't happen before when I had it set to `ignore "Task Manager";` and switching it back to this no empty tile is opened. The remaining ignore commands work as expected.

**Comment by keepitsane** [comment]
Running Nog with admin privilege seems to fix this issue.

**Comment by keepitsane** [comment]
Also I think if Nog ignores an application the user should still be able to manually toggle floating mode. Currently if an application is listed to be ignore it is impossible to get Nog to manage it should they need to after the fact. Not sure if this is the expected behavior.

**Comment by TimUntersberger** [comment]
> I can open another issue if you would like me to

👍 

> Also I think if Nog ignores an application the user should still be able to manually toggle floating mode. Currently if an application is listed to be ignore it is impossible to get Nog to manage it should they need to after the fact. Not sure if this is the expected behavior.

Please open a seperate issue for this and yes it *should* work like that.
