### ISSUE TITLE
Nog is still called WWM in notification area

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#131]
**Version (which release did you use?)
c8ee70b - Development Build

**Describe the bug**
Nog is still call WWM in notification area.

**To Reproduce**
1. Go to notification area
2. Hover mouse over nog icon
4. Shows WWM

**Expected behavior**
It should show NOG

**Actual behavior**
It shows WWM

**Comment by TimUntersberger** [comment]
Thank you!
