### ISSUE TITLE
OS module

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#140]
Should contain general information about the operating system like battery life, cpu usage and so on.

Things I want to include: 

* battery life
* whether you are using ac power
* cpu usage
* memory usage

If you want anything else included please tell me.

**Note**: Temperatures will not be included for now, because they require a lot more work then these basic ones.

## Battery

[GetSystemPowerStatus](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getsystempowerstatus) can be used to get the battery status and whether you are using ac.

## Memory

General information about memory usage can be retrieved with the [GlobalMemoryStatusEx](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex) function.

## Cpu

[GetSystemTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtime) can be used to calculate the CPU usage.

**Comment by ramirezmike** [comment]
I was considering taking a look at implementing a couple of these following the existing component patterns, maybe starting with the battery one first. Would it be correct to assume that any extra components made won't add significant refactor time to future changes in the config language or component setup?

**Comment by TimUntersberger** [comment]
> Would it be correct to assume that any extra components made won't add significant refactor time to future changes in the config language or component setup?

I don't think so.

**Comment by system32uwu** [comment]
How can we implement a battery component? Not sure how to use the library you linked in Lua

**Comment by TimUntersberger** [comment]
libuv documentation: https://github.com/luvit/luv

to use the library you have to require it: `local luv = require 'luv'`

I think the easiest way would be to just execute the following shell command and parse the result:

```powershell
(Get-WmiObject win32_battery).estimatedChargeRemaining
```

and I don't think you would need libuv for that.

**Comment by system32uwu** [comment]
Thank you, I'll be checking this out this weekend.

**Comment by TimUntersberger** [comment]
```lua
local uv = require 'luv'
-- local handle = uv.spawn([[(Get-Item "HKLM:SOFTWARE\Microsoft\Windows NT\CurrentVersion").GetValue('ReleaseID')]], { stdout, stderr }, function(code, signal)
--   print(code, signal)
-- end)
-- local handle, err = uv.spawn('cmd.exe', { args = { "/C", "echo", "test" }, stdio = { stdout, stderr }}, function(code, signal)end)

local function shell(args, options)
  local raw_args = { "/C" }

  if type(args) == "string" then
    local part = ""
    for i=1,#args do
      local c = args:sub(i, i)
      if c == " " then
        table.insert(raw_args, part)
        part = ""
      else
        part = part .. c
      end
    end
    table.insert(raw_args, part)
  elseif type(args) == "table" then
    for i=1,#args do
      table.insert(raw_args, args[i])
    end
  end

  local stdout = uv.new_pipe(false)
  local stderr = uv.new_pipe(false)
  local stdin = uv.new_pipe(false)
  local handle, err = uv.spawn('cmd.exe', { args = raw_args, stdio = { stdin, stdout, stderr }, verbatim = false, hide = true }, function(code, signal)
    print(code, signal)
  end)

  if type(err) == "string" then
    error(err)
  else
    uv.read_start(stdout, function(err, data)
      print(stdout)
    end)
    uv.read_start(stderr, function(err, data)
      print(stderr)
    end)
  end
end

shell({"echo", "test"}, {
  on_stdout = function(err, data)
    print(#data)
  end
})

```

Played with this myself a bit, but I can't seem to get the process running. Thought I'd post this to give you a better starting point.

**Comment by TimUntersberger** [comment]
@system32uwu if you manage to implement this, please post the solution to this issue.
