### ISSUE TITLE
Grids offset by taskbar on launch if user has set remove_task_bar in config

### ISSUE THREAD

**Issue by ramirezmike** [TimUntersberger/nog#152]
**Version (which release did you use?)**
ce4eb76 on development branch

**Describe the bug**

If the user has "enable remove_task_bar" in their config when launching nog, workspaces will be offset by the size of the taskbar until the user toggles visibility of the taskbar.

**To Reproduce**

1. Set config "enable remove_task_bar"
2. Restart nog
3. Manage a window in a workspace
4. Note the window doesn't take up the full space of the view

**Expected behavior**

Managed windows should take up space available if the taskbar is hidden

**Actual behavior**

Managed windows don't fill the taskbar space if nog is started with the taskbar hidden

**Comment by ramirezmike** [comment]
This should be resolved by https://github.com/TimUntersberger/nog/pull/153

**Comment by ramirezmike** [comment]
@keepitsane this should resolve the issue you were describing about the workspaces not using available room from a hidden taskbar

**Comment by keepitsane** [comment]
![image](https://user-images.githubusercontent.com/13246774/92313070-2c436000-ef95-11ea-8fea-8a0902501b88.png)

Hmm still seem to be getting the bug with the latest dev build.

**Comment by ramirezmike** [comment]
@keepitsane interesting.. 

1) Can you tell me more about your setup and what your config file looks like and where you keep your taskbar (I'm assuming bottom)? 
2) I know this might seem like a silly question but that screenshot is definitely your browser managed by nog, is that correct? Is that like... you started nog and then launched the browser and managed it manually or do you have it set to automanage? 

I did notice the issue on my machine after changing the config, this looks pretty similar to what you're seeing, I think. This is on my build left is the commit before the changes and right is the latest development release build. Steps were... taskbar at the bottom of the screen, start nog with config to hide taskbar & show appbar and then I opened notepad and let nog automanage it.

![comparison](https://user-images.githubusercontent.com/1421719/92313548-fdc88380-ef9a-11ea-9012-bd31aa26ea18.jpg)

**Comment by keepitsane** [comment]
1. My config file follows the same structure as the example one provided and yes my taskbar is at the bottom.1. My config file follows the same structure as the example one provided and yes my taskbar is at the bottom.
```
import "nog/components" as C;

import "modes/resize";
import "keybindings";
import "rules";

set min_height 200;
set min_width 200;

bar #{
font: "FiraCode NF",
font_size: 17,
color: 0x4B326E,
components: #{
left: [C::workspaces()],
center: [C::time("%l:%M:%S %p")],
right: [C::active_mode(), C::padding(5), C::date("%e %b %Y"), C::padding(1)]
}
};

disable work_mode;

enable launch_on_startup;
enable multi_monitor;
enable display_app_bar;
enable remove_title_bar;
enable remove_task_bar;

workspace 4 #{
monitor: 1,
};
workspace 5 #{
monitor: 1,
};
workspace 6 #{
monitor: 1,
};
workspace 7 #{
monitor: 2,
};
workspace 8 #{
monitor: 2,
};
workspace 9 #{
monitor: 2,
};
```

2. Yes browser being managed by Nog. I start Nog and have a keybind to open my browser and a custom rule for firefox.
```
rule "firefox.exe" #{
    has_custom_titlebar: true,
    firefox: true
};
```

**Comment by ramirezmike** [comment]
Ah! Got it! Thanks, @keepitsane 

>disable work_mode;

I think this is the clue, because the code to handle setting up the appbar/taskbar when nog starts first checks to see if work_mode is enabled. 

I suspect the code that runs when work_mode gets enabled needs to be modified. I'll see if I have some time for that today. In the mean time, the work around is again to either toggle the taskbar or change the config to enable work_mode. Thanks for providing your config and the log file, that helped a ton!

**Comment by TimUntersberger** [comment]
@keepitsane does the newest build fix this for you?

**Comment by keepitsane** [comment]
@TimUntersberger it fixes the bug on my two secondary monitors, but not my primary monitor.

**Comment by keepitsane** [comment]
I am not sure if you changed anything in the last dev build you pushed, but the bug seemed to have gone away. Will continue to test before closing.

**Comment by keepitsane** [comment]
I think it is safe to close this issue now, I haven't experienced this bug any more.
