### ISSUE TITLE
A suspicious use of `const` `AtomicBool`

### ISSUE THREAD

**Issue by rail-rain** [TimUntersberger/nog#156]
Hello, 

I noticed you're applying `store` and `load` to a constant, and I think you actually want a `static` item [because `const ` atomics are not global mutable states](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_interior_mutable_const). However, I'm not familiar with the code base so I might get it wrong.
https://github.com/TimUntersberger/nog/blob/c587c016e7f1225f8422f06d5fd596ba4cd38f21/src/update.rs#L7

By the way, what an interesting project and the great amount of work! ~~I had no idea one can make a window manager for WIndows 10~~.

**Comment by TimUntersberger** [comment]
The code is still WIP (As you can see with the `todo!`). It got pushed accidentally, but nice catch with the const!

**Comment by TimUntersberger** [comment]
> By the way, what an interesting project and the great amount of work! ~~I had no idea one can make a window manager for WIndows 10~~.

Thank you!
