### ISSUE TITLE
Moving a window to a different workspace that hasn't been initalized doesn't follow config file

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#158]
Lets say in my config file I have workspace 2 assigned to be on my secondary monitor and I have a window that exists in workspace 1 on my primary monitor. This bug happens when I try MoveToWorkspace on a workspace that I haven't visited yet/activated. 

If I execute my MoveToWorkspace on that window to move it from workspace 1 to workspace 2 it works, but Nog creates workspace 2 on my primary monitor rather than following my config file in which I have workspace 2 assigned to my secondary monitor. If I visit workspace 2 with my ChangeWorkspace keybind first before running MoveToWorkspace the workspace is created on the current monitor assigned in my config file.

Not sure if my description is a bit confusing, if it is let me know and I can try to record a video of the bug and upload that.

**Comment by TimUntersberger** [comment]
I can't reproduce this.

I have workspace 2 set to my secondary monitor.

Steps

1. Go into work mode
2. Open notepad in workspace 1
3. Use MoveToWorkspace to move the window to workspace 2

This results in workspace 2 being opened in my secondary monitor.

**Comment by keepitsane** [comment]
Seems to be fixed in the latest version.
