### ISSUE TITLE
Can't use the same keybinding across modes

### ISSUE THREAD

**Issue by ramirezmike** [TimUntersberger/nog#167]
**Version (which release did you use?)**
Development branch e87df585422d7c27516b1c9b5b27a46731fed05c

**Describe the bug**

If you configure the same keybinding to do different actions in two different modes, nog will only use the first mode's (first loaded in the config) keybinding, even if you're not in the first mode. 

**To Reproduce**

1. Create two modes and load them in the config
2. In the 1st mode, bind a keybinding to some action
3. In the 2nd mode, bind the same keybinding to a different action
4. Run nog and start the 2nd mode and use the keybinding

**Expected behavior**

The action bound to the keybinding in the 2nd mode should "fire"

**Actual behavior**

The action bound to the keybinding in the 1st mode "fires"

The problem, I believe, happens in src/keybindings.rs get_keybinding function. That function does a find on the stored keybindings and returns the first one, but doesn't factor in if the user is currently in a mode.

I was able to "resolve" the issue in my WIP pull request [here](https://github.com/TimUntersberger/nog/pull/164/files#diff-80b43c45ca77d60aa283420f10366736) but I believe it's a flawed approach. Basically, it checks the current active mode and filters the keybindings to only those that match the mode before performing the find. This fixes the issue BUT it introduces a new one: the keybinding to exit the mode is not marked as belonging to the mode. 

The hack I did here is to check in the filter is 
A) a keybinding whose mode matches the current mode 
OR 
B) a keybinding for toggling the current mode (and if there is no current mode then a fabricated keybinding of toggling a mode "none")

I think the _real_ solution would be to do something in the rhai code to add the togglemode keybinding under the mode's set of keybindings, but I'm not really familiar with that part of the code base yet.

**Comment by TimUntersberger** [comment]
This should be fixed in `cross-platform`
