### ISSUE TITLE
Triggering IncrementConfig, DecrementConfig and ToggleConfig while in a mode causes keybinding issues

### ISSUE THREAD

**Issue by ramirezmike** [TimUntersberger/nog#168]
**Version (which release did you use?)**
Development branch e87df58

**Describe the bug**

Because IncrementConfig, DecrementConfig and ToggleConfig all modify the in-memory config object, triggering them while a mode is active causes nog to become unresponsive in some ways. It won't respond to key commands but you can still switch workspaces by clicking the workspace number and the timer component keeps ticking.

**To Reproduce**

1. Create a mode and add a keybinding for either IncrementConfig, DecrementConfig or ToggleConfig 
2. Run nog and activate the mode, then press the keybinding configured in step 1

**Expected behavior**

The keybinding action should occur successfully and nog should keep running

**Actual behavior**

All keybindings stop working

**Notes**
I haven't dug too deeply into this but it happened to me today after I added a IncrementConfig/DecrementConfig keybinding for padding/margin to my resize mode. I suspect it's because those three functions call the src/hot_reload.rs update_config function and it might just get weird with the registering/unregistering keybindings while still in a mode?

**Comment by TimUntersberger** [comment]
I think it would be best to look at this after the `cross-platform` stuff is merged, since it tries to minimize the `lock` usage and overall global state.

**Comment by TimUntersberger** [comment]
This should be fixed in `cross-platform`.
