### ISSUE TITLE
[Feature Request] Some kind of IPC mechanism

### ISSUE THREAD

**Issue by takase1121** [TimUntersberger/nog#170]
When I was trying to add a component, I really hit the limit of what the engine can do. Things run synchronously and there are no timers, no way to interact with OS, no way to interact with nog. etc etc. 

Some of the issues can be added later on, but there is just a limit what rhai can do. A way to send messages to nog would be really nice. AFAIK some wm on Linux has a client that sends message to the wm. That would be really nice addition for nog.

**Comment by TimUntersberger** [comment]
> no way to interact with OS

An initial OS module is in the `os` branch. I never really had the time to finish it.

> Things run synchronously

I will probably add a `thread` keyword that just runs the code inside a block async.

```nog
thread {
  // async
}
```

> A way to send messages to nog would be really nice

What would be your usecase for this? Maybe something like an http endpoint would be nice to explore.

> When I was trying to add a component, I really hit the limit of what the engine can do

Can you show me some examples that are not related to async/sync stuff?

**Comment by takase1121** [comment]
> I will probably add a thread keyword that just runs the code inside a block async.

I think the author of rhai is adding threads to rhai, but it will be a post 1.0.0 feature.

> What would be your usecase for this? Maybe something like an http endpoint would be nice to explore.

- in DWM, `xsetroot` allows user to set the text on the bar. I used it to set my MOTD with marquee effect. [shameless self promotion](https://www.reddit.com/r/unixporn/comments/gipm1n/dwm_i_mean_you_have_to_start_somewhere_dont_you/)
- in polybar, IPC can be used to hide/unhide, or set hooks in config to do something. Combined with Rhai, this could be very useful. Changing session-specific settings might also be a good use for IPC.
- in i3, IPC can be used to manage the WM itself. Maybe you have a program that detects fullscreen apps / screen change and automatically move workspaces to another screen or something?

My usecase is to bring that marquee MOTD bar from DWM to nog. Currently, rhai lacks some construct to do it (eg. HTML parsing, timers) which can be fixed with a bash script sending the formatted string directly to nog. 

> Can you show me some examples that are not related to async/sync stuff?
My main complaints was about async/sync. Other than that, I don't actually any problems with it, its quite powerful.

**Comment by TimUntersberger** [comment]
The thing about the IPC stuff is that I believe most of the usecases can (should) be achieved using just the config file.

For example your MOTD could be a custom component given more customization options for components.

> Changing session-specific settings might also be a good use for IPC

This can already be done.

> HTML parsing

We could provide a module for that

> timers

Same thing here

Could you please open separate issues for each new thing? (html parsing, timers, ....)

**Comment by TimUntersberger** [comment]
@takase1121 I added "async" support (https://timuntersberger.github.io/nog/#/scripting/async)

**Comment by TimUntersberger** [comment]
Once `cross-platform` gets merged, all callbacks provided by the user now are async by default (Makes more sense to me)

**Comment by TimUntersberger** [comment]
I will be closing this as I want to avoid implementing something like this. If we find something that will require this we can reopen it.

**Comment by TimUntersberger** [comment]
@takase1121 I want to implement [plugins](https://github.com/TimUntersberger/nog/issues/173) before adding support for html parsing. The idea is that the plugins are implemented in nog script instead of rust. I just need to give this some more thought, but I believe this would be possible.

Regarding the marquee effect: could you open a new issue requesting for this? Maybe we should somehow support animations for bar components?
