### ISSUE TITLE
Cant clear syntax error popup

### ISSUE THREAD

**Issue by taylan97** [TimUntersberger/nog#185]
**Version (which release did you use?)**
4f07a44cc15fe09b6603630d3547e68a6d55193f development release

**Describe the bug**

**To Reproduce**

1. Drop a semicolon from a line in config file, save file.

2. Fix semicolon, (reload nog?)

**Expected behavior**

Syntax error popup disappears.

**Actual behavior**

Syntax error popup remains until I log out or restart my computer. Even if Nog is quit.

**Comment by taylan97** [comment]
While the `alt-q` bind works sometimes, I think there is still a bug with nog not resolving focus after a configuration error. Half the time it will accept and clear the popup, the rest of the time it refuses to accept any input (workmode on/off, close tile, etc) and there's no way to 'focus' it.

**Comment by ramirezmike** [comment]
I encountered the same issue @taylan97 mentions above and when I went through the commits and it seems it was introduced with the changes for #185. I opened #189 to address it, so this might not be worth re-opening but just letting @taylan97 know #189 will be used to track this. 

I'm hoping I can get this resolved soon.
