### ISSUE TITLE
Custom language

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#191]
I am currently creating a custom language just for nog, because I am no longer really happy with `rhai`, because the philosophy of the project does not really align with how I imagine the config to be.

You can follow the progress in the [custom-language](https://github.com/TimUntersberger/nog/tree/custom-language) branch.

This issue is for discussing the design of the language.

Things I want to do/add can be seen in this [project](https://github.com/TimUntersberger/nog/projects/2)

**Comment by TimUntersberger** [comment]
I am not sure whether continuing with using keywords to configure nog is a good idea.

## example

### keyword
```nog
bind "Alt+H" focus("left");
```

### function

The bind function takes a key combination and a function. When the combination gets pressed the function gets called.
This makes keybindings very flexible with a slight cost of having to type more.

```nog
nog.bind("Alt+H", nog.api.window.focus_left);
nog.bind("Alt+F1", () => {
    nog.api.window.focus_left();
    nog.api.window.focus_up();
});
```

**Comment by TimUntersberger** [comment]
Overall I now want to avoid using keywords for this kind of configuration and strive more towards something like writing a config file for neovim in lua.

**Comment by keepitsane** [comment]
While a bit more verbose the `function` approach does seems the way to go, especially for the scripting and plugin functionality that you have been working on. Question though if you switch away from rhai, wouldn't that add a major roadblock for the above mentioned plugin functionality? 

Additionally, here is a pretty cool blog series about making a programming language using Rust: [https://arzg.github.io/lang/](https://arzg.github.io/lang/). Obvious a bit overkill since you are only making a scripting language, but maybe you can glean some potential helpful information.

**Comment by TimUntersberger** [comment]
> Question though if you switch away from rhai, wouldn't that add a major roadblock for the above mentioned plugin functionality

It is kind of, but I have most of the functionality down and would only need to adapt the RC plugin system to our own engine.

> Additionally, here is a pretty cool blog series about making a programming language using Rust: https://arzg.github.io/lang/. Obvious a bit overkill since you are only making a scripting language, but maybe you can glean some potential helpful information.

I used this exact blog for getting started with the ground work 👍

**Comment by TimUntersberger** [comment]
The newest commit on the `custom-language` branch now has function mappings working.

example
```nog
import nog

print(nog.version)

nog.map("Enter", () => {
    print(range(10))
})
```

Once I implement import layers the code could look like this.

```nog
import nog
import nog.map

print(nog.version)

map("Enter", () => {
    print(range(10))
})
```

I am thinking about renaming the `map` function to `bind`, so that it won't get confused with the array `map` function.

I also went with an optional semicolon style. I'd like some feedback on that @keepitsane @ramirezmike

**Comment by ramirezmike** [comment]
I don't mind the absence of semicolon for the configuration. I definitely have tripped up already by omitting the semicolon when changing my existing config, hah. So, would it essentially treat new lines as the end of statements or would you be able to have multiple statements on one line like this?

`print(range(10)) print(range(10))`

Not saying it should behave that way, just curious how it does behave.

It's looking good so far. Clean and approachable.

**Comment by keepitsane** [comment]
Yeah I agree with  @ramirezmike optional semicolon is the way to go. I think following vim like config rule should be the most comfortable.

**Comment by TimUntersberger** [comment]
> So, would it essentially treat new lines as the end of statements

A line ending is defined by some rules that are handwritten into the parser, meaning that your example works because an `identifier` can't follow a `closing parenthesis`.

> I think following vim like config rule should be the most comfortable.

 Can you elaborate? What do you mean by `vim like config rule`

**Comment by TimUntersberger** [comment]
How should I namespace the APIs?

`nog.api.window.get_title` or `nog.window.get_title`

**Comment by ramirezmike** [comment]
I guess with nog.api I would just wonder what is under the nog "object" that wouldn't be under the api one.

**Comment by TimUntersberger** [comment]
I think we should also change the file ending from `nog` to something different like `ns` (nogscript) or whatever to make it easier to know what someone talks about when saying `nog` (window manager or language).

**Comment by TimUntersberger** [comment]
This is what my current `keybindings.ns` file looks like.

```nogscript
import nog

var workspace_count = 10
var direction_keys = #{
    "H": "Left",
    "J": "Down",
    "K": "Up",
    "L": "Right",
}


/// This function prepends each item of the provide array with the given modifier 
/// and binds it to `f(item)`
fn bind_arr(mod, f, arr) {
    arr.for_each(i => {
        nog.bind(mod + "+" + i, () => f(i))
    })
}

/// This function prepends each key in the provided object with the given modifier 
/// and binds it to `f(map[key])`
fn bind_map(mod, f, map) {
    map.keys().for_each(key => {
        nog.bind(mod + "+" + key, () => f(map[key]))
    })
}

nog.bind("Alt+I", nog.window.ignore)
nog.bind("Alt+Q", nog.window.close)
nog.bind("Alt+M", nog.window.minimize)
nog.bind("Alt+X", nog.quit)

bind_map("Alt", nog.workspace.find, direction_keys)
bind_map("Alt+Control", nog.workspace.swap, direction_keys)

nog.bind("Alt+Plus", () => nog.window.set_split_direction("Vertical"))
nog.bind("Alt+Minus", () => nog.window.set_split_direction("Horizontal"))

nog.bind("Alt+Control+F", nog.window.toggle_floating)
nog.bind("Alt+Control+W", nog.toggle_work_mode)
nog.bind("Alt+F", nog.workspace.toggle_fullscreen)

bind_arr("Alt+Shift", nog.window.move_to_workspace, range(workspace_count))
bind_arr("Alt+Control", nog.workspace.move_to_monitor, range(workspace_count))
bind_arr("Alt", nog.workspace.change, range(workspace_count))

```

This still feels very nice to write. Any thoughts?

`///` is documentation and `//` is a comment.

**Comment by TimUntersberger** [comment]
I am sure how to approach rules yet.

My current idea is to have something like the following, where `false` means to ignore the window.

```nogscript
var rules = #{
    "explorer.exe": false,
    "Taskmgr.exe": false,
    "SnippingTool.exe": false,
    "firefox.exe": #{
        has_custom_titlebar: true,
        workspace_id: 2,
        firefox: true
    }.
    "Discord.exe": #{
        has_custom_titlebar: true
    },
    "Spotify.exe": #{
        has_custom_titlebar: true
    },
    "Code.exe": #{
        has_custom_titlebar: true
    },
    "chrome.exe": #{
        has_custom_titlebar: true,
        workspace_id: 2,
        chromium: true
    },
}

```

**Comment by ramirezmike** [comment]
### Regarding keybindings.ns comment
here are some of my thoughts:

- are variables mutable?
- bind_arr and bind_map seem useful enough that they should just be part of the nog api. Is that your intention? 
- where is that range function coming from?
- for things like this where the function you pass in is one line
```
nog.bind("Alt+Plus", () => nog.window.set_split_direction("Vertical"))
```
I'm assuming you can do stuff across multiple lines like this?
```
nog.bind("Alt+P", () => {
    nog.workspace.increment_config("inner_gap", 20)
    nog.workspace.increment_config("outer_gap", 20)
})
```
- is there if/else for branching?
- there are a couple spots where I'd think functions are on window/workspace when they should be on the other like.. nog.workspace.toggle_fullscreen. Shouldn't that be on window? and nog.window.set_split_direction maybe on workspace? Not sure..
- this is a bit of a stretch, I think, but do those functions behave like closures that capture variables to have some sort of state like this?
```
var split_toggle = false
nog.bind("Alt+T", () => {
    if split_toggle {
        nog.window.set_split_direction("Vertical")
    } else {
        nog.window.set_split_direction("Horizontal")
    }
    split_toggle = !split_toggle
});
```

And some other, sorta unrelated thoughts:
- what is nog.workspace.find?
- workspace_count = 10 reminded me that we could consider increasing nog's max grid count to handle more if the user wants to make additional keybindings for like 11-20 or whatever

### Regarding rules comment

I dig it one thing that I want to point out is that with "false" meaning ignore you wouldn't be able to setup rules on a program that you want to initially be unmanaged. Like, maybe someone wants chrome to be floating when they open... but when they do manage it, they want it to have has_custom_titlebar: true. Also, what if they want it managed but no other rule? Would that be like "notepad.exe": true ?

Overall though, I like the direction this is going in and am excited.

**Comment by ramirezmike** [comment]
I thought about this a little more and on the point above where I wrote this

```
var split_toggle = false
nog.bind("Alt+T", () => {
    if split_toggle {
        nog.window.set_split_direction("Vertical")
    } else {
        nog.window.set_split_direction("Horizontal")
    }
    split_toggle = !split_toggle
});
```

It may not be necessary to have the mutable variable captured by the closure if we just have add more state querying to the API like this

```
nog.bind("Alt+T", () => {
    if nog.window.get_split_direction() == "Horizontal" {
        nog.window.set_split_direction("Vertical")
    } else {
        nog.window.set_split_direction("Horizontal")
    }
});
```

I imagine there would be other scenarios like that, but... that would at least require if/else and logical comparison operators to work.

**Comment by TimUntersberger** [comment]
> are variables mutable?

Yes. 

> bind_arr and bind_map seem useful enough that they should just be part of the nog api

👍 

> where is that range function coming from?

This function is in the prelude. Do you think it should be manually imported?

> I'm assuming you can do stuff across multiple lines like this?

Yes.

> is there if/else for branching

Yes.

> there are a couple spots where I'd think functions are on window/workspace when they should be on the other like.. nog.workspace.toggle_fullscreen. Shouldn't that be on window? and nog.window.set_split_direction maybe on workspace? Not sure..

`toggle_fullscreen` is in workspace, because the workspace goes into fullscreen mode and not the window. Moving the window doesn't transfer the fullscreen state, so I think this would be confusing.

`set_split_direction` is in window, because each window has its own split_direction.

> this is a bit of a stretch, I think, but do those functions behave like closures that capture variables to have some sort of state like this?

This is possible.

> add more state querying to the API

This is on the TODO 👍

**Comment by TimUntersberger** [comment]
I am actually more leaning towards something like below

```nogscript
import nog

nog.rules
    .ignore("explorer.exe")
    .ignore("Taskmgr.exe")
    .ignore("SnippingTool.exe")
    .match("firefox.exe", #{
        has_custom_titlebar: true,
        workspace_id: 2,
        firefox: true
    })
    .match("chrome.exe", #{
        has_custom_titlebar: true,
        workspace_id: 2,
        chromium: true
    })
    .match("Discord.exe", #{
        has_custom_titlebar: true,
    })
    .match("Spotify.exe", #{
        has_custom_titlebar: true,
    })
    .match("Code.exe", #{
        has_custom_titlebar: true,
    })
```

**Comment by ramirezmike** [comment]
>Do you think it should be manually imported?

Eh, it's probably fine if it's clear where it comes from.

Regarding the rules, I almost prefer the example you posted before, it seemed a little less verbose and you wouldn't need to worry about naming "match", it's kinda implied.

I also think this approach wouldn't allow someone to configure an app to be ignored but also configure other rules in case they want to manually manage.

If someone wanted to setup chrome so that nog doesn't manage it automatically, but if it does get managed they'd want the other rules to apply

```
ignore("chrome.exe")
match("chrome.exe", #{
    has_custom_titlebar: true,
    workspace_id: 2,
    chromium: true
})
```

versus

```
var rules = #{
    "chrome.exe": #{
        has_custom_titlebar: true,
        ignore: true, // defaults to false so you opt into this when setting up rules
        chromium: true
    },
}
```

**Comment by TimUntersberger** [comment]
Quick update.

The plugin system seems to be working fine now. I have an example plugin [here](https://github.com/TimUntersberger/counter.nog).

The plugin can be installed like this `nog.plugin.install("TimUntersberger/counter.nog")` and used like this:

```nogscript
import counter

nog.bar.configure(#{
  components: #{
    left: [counter.component]
  }
})
```

**Comment by ramirezmike** [comment]
1. I started thinking about what would be needed exposed on the nog.window api in order to be able to write a plugin/scripts/bindings to do the kinds of things I mentioned in #203 

I'd want to start with some functions to get information about the tiles surrounding the focused tile like.. (naming just off the top of my head)

       window.adjacent_info("left") 
       or maybe
       window.left.info


Which would return just either "Column", "Row", "Tile" or None or some enum representing them? Maybe it can return a "window" too, although I don't know what column/row would be in that sense.

This would allow writing some context-aware movements like swapping a tile to the left with neighboring tiles but if you've reached the end (where the tile is in the 0th position of its column parent) and the item to the left is a row then push into that row.

    AAADDEEFF       AAADDFFEE     AAAFFDDEE       AAADDDEEE       
    BBBDDEEFF  ->   BBBDDFFEE  -> BBBFFDDEE   ->  BBBDDDEEE
    CCCDDEEFF       CCCDDFFEE     CCCFFDDEE       CCCDDDEEE
                                                  FFFDDDEEE 
                                                  
^ F column moving left as it detects tiles and then moving into the row when it hits a row but all with the same key binding

I'm thinking start there + the existing bindings and then writing some scripts to see what works or what else we might need. If that seems sane I can start working on adding that.

2. It might be good to keep an updated config.ns either pasted here or in the repo. I pieced some of it together but it took a bit to figure out what was implemented and what wasn't

3. I'm excited for these changes. I keep thinking of things that would be nice like a "close workspace" keybinding that automatically quits all the programs on a workspace and then I think "ah that can be scripted on the new branch"

**Comment by TimUntersberger** [comment]
Are you talking about organizers being implemented in nogscript?

> It might be good to keep an updated config.ns either pasted here or in the repo. I pieced some of it together but it took a bit to figure out what was implemented and what wasn't

I am now beginning to rewrite the documentation for the new language.

**Comment by ramirezmike** [comment]
Yeah, as like either plugins or even just bindings in users' config.ns or imported ns files
