### ISSUE TITLE
Won't recognize keybindings if one fails to register

### ISSUE THREAD

**Issue by meluskyc** [TimUntersberger/nog#198]
**Version (which release did you use?)**
Develop branch 7fbe44c

**Describe the bug**

If a keybinding fails to register, Nog will continue running but won't recognize any keybindings.

(added a dbg! to line 121)
```
[src\keybindings.rs:121] &kb = Keybinding(ALT+CONTROL+J, Swap, 3074, None)
thread '<unnamed>' panicked at 'Failed to register keybinding: Null', src\system\win\api.rs:183:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/8256379832b5ecb7f71e8c5e2018446482223c12\/library\core\src\option.rs:1268
   3: core::result::Result<i32, nog::system::win::WinError>::expect<i32,nog::system::win::WinError>
             at C:\Users\melus\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:933
   4: nog::system::win::api::register_keybinding
             at .\src\system\win\api.rs:177
   5: nog::keybindings::{{impl}}::start::{{closure}}
             at .\src\keybindings.rs:123
```

In this case, I already had CTRL-ALT-J registered to JetBrains Toolbox. Removing that keybinding fixed the issue.

**To Reproduce**

Register a keybinding with another application. Then try to run Nog with the same keybinding in `config.nog`. 

**Expected behavior**

Nog continues to run OK without the bad keybinding. Or Nog exits and tells the user there was an error. 

**Actual behavior**

Nog is still running but will not recognize any keybindings.

**Comment by ramirezmike** [comment]
This sounds just like what @mdkozlowski is encountering in #190. It's even the same key binding. I am curious what happens if nog is launched first. 

I think ideally if this happens nog should continue running but throw a popup indicating what keybinding(s?) weren't able to be registered.

**Comment by meluskyc** [comment]
FYI -- if I run nog first, nog's keybinding takes precedence and everything works OK.

**Comment by ramirezmike** [comment]
@meluskyc 

I added some code to trigger a popup showing what keybinding failed to register. It looks like this:

![popup](https://user-images.githubusercontent.com/1421719/101120559-eb6edd80-35bb-11eb-831e-f071ea791698.png)

You should be able to use all other keybindings that aren't conflicting with other applications when this occurs. Check out the latest development release and let me know if that works for you.

**Comment by meluskyc** [comment]
Fixed now. Thanks!
