### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#201]
provide various testing functions in std.test like expect, it, group, equal

**Comment by TimUntersberger** [comment]
I have given this some more thought and I think going for a more functional approach would be a good way to go.

So instead of having something like in rust where you annotate a function with `#[test]` to tell cargo that this is a test, you instead import various helper functions which can be used to build your test suite. (If you have used rspec before you should be familiar with this)

Functions that are used to structure your tests

* describe
* it
* when

Assertion functions

* assert_true
* assert_false
* assert_eq
* assert_neq

These functions live in the `test` module, which is only included in the runtime when running a program using the cli (which still has to be implemented).

`nog test`

**Comment by TimUntersberger** [comment]
@ramirezmike @keepitsane any thoughts regarding this?

**Comment by ramirezmike** [comment]
Just to be clear, this is for testing nogscripts, correct? I think it's an interesting idea but I'm curious how it will be used. Is this something that nog users would use? Like.. to test their scripts while running nog in this test mode? Am I understanding that correctly?

**Comment by TimUntersberger** [comment]
This is something completely separated from nog and only regards nogscripts. This is more for plugin developers to test their code easily.

Maybe this is a bit too much for a window manager.

**Comment by ramirezmike** [comment]
Yeah, it seems like it could be neat but it really depends on what kind of things the nogscripts would do and how heavily they may be modified/updated.

**Comment by keepitsane** [comment]
Yeah i agree I think it would be a nice to have, but might be a bit overkill for right now. 😄
