### ISSUE TITLE
[Suggestion] Migrate to Microsoft's official Windows API crate from winapi

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#216]
Obviously not 100% needed as winapi seem to be working fine for now, and I know you also spent time writing a custom layer on top. But figured I would mention it since it is the official Microsoft crate and it just went live this week I believe. It also supports all versions of the Windows API and if I had to guess would offer better future support as a first party offering compared to winapi. 

Like I mentioned it may not be needed as of right now, but it could help simplify future development especially if some WinRT bindings are needed for future features.

Here is the GitHub repo and crates link:
https://github.com/microsoft/windows-rs
https://crates.io/crates/windows

**Comment by TimUntersberger** [comment]
I don't really see any point as of now. If in the future the `winapi` crate is deprecated and no longer suffices, we could reopen this issue and swap to `windows-rs`.

Closing this for now.
