### ISSUE TITLE
Should we remove development branch?

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#223]
I think we don't need a separate branch for development, because stable version can be saved by creating a new release.

Having to constantly create PRs from `development` into `master` just to sync docs is really annoying.

@ramirezmike any thoughts?

**Comment by ramirezmike** [comment]
I think that's fair and agree as long as there is a clear "this is the latest stable version" vs whatever happens to be in master. The only weirdness would be if the master branch happens to have doc changes of features that aren't in the latest stable release... but I'm not sure how often that would happen/how big of a deal that is. A note saying "WIP docs may reference features not yet in stable" or whatever would probably suffice.

**Comment by TimUntersberger** [comment]
@ramirezmike do you have any branches that are based on development?

**Comment by ramirezmike** [comment]
Every branch I have has been merged so if there is anything dependent on **development** it should be fine to be deleted.

**Comment by TimUntersberger** [comment]
I updated all of the workflows and the documentation. The `development` branch is now also deleted.
