### ISSUE TITLE
Documentation front page opens print dialog

### ISSUE THREAD

**Issue by Gskartwii** [TimUntersberger/nog#225]
When visiting the [Nog documentation](https://timuntersberger.github.io/nog/) on GitHub Pages, I am presented with an unexpected print dialog.

I found the [JS code responsible](https://github.com/TimUntersberger/nog/blob/f08455df60131eb5475bf4d8f061b3522fa32fe3/docs/index.html#L711-L715) for this by looking around the GitHub repo, but I can't find out where it's generated:

https://github.com/TimUntersberger/nog/blob/f08455df60131eb5475bf4d8f061b3522fa32fe3/docs/index.html#L711-L715

P.S. The dialog caught me off guard and I got a good laugh out of this. What on earth is it doing there?

**Comment by TimUntersberger** [comment]
Wait what LOL

**Comment by TimUntersberger** [comment]
It looks like this always gets rendered? I am actually really confused right now.

[reference](https://github.com/rust-lang/mdBook/blob/0b9570b160d0dd612f7140730c682c0c07640c85/src/theme/index.hbs#L297)

**Comment by ramirezmike** [comment]
@TimUntersberger what are the steps you use to generate the docs? I tried to follow along with what you used to have in the github actions script but I was missing a couple files, like a book template file? I was assuming you were manually generating and dropping in the print view output because it was the route that you could get working right lol

**Comment by TimUntersberger** [comment]
@ramirezmike I am using the `build_docs.ps1` script to generate the docs.

**Comment by TimUntersberger** [comment]
Fixed in #231. For anyone encountering this issue: 

The problem was that you NEED to have the `README.md` file referenced in the `SUMMARY.md` file else mdbook won't generate an index.md file. I though the `print.html` is the index.html so I just renamed it.
