### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/nog#235]
- [ ] how to write a plugin
- [ ] how to write custom components
- [ ] builtin classes
- [ ] Documentation syntax
- [x] nog.bar in API section

**Comment by keepitsane** [comment]
Do you have any personal examples of how you are using this feature? I was attempting to thing of potential plugin ideas, but wasn't sure of something that could be useful. Any suggestions would be appreciated!

**Comment by TimUntersberger** [comment]
I implemented a [Counter component](https://github.com/TimUntersberger/counter.nog) as a plugin just to see how writing a plugin would feel.

**Comment by keepitsane** [comment]
Yeah I saw that, but do you have a real-world idea of a plugin people might want to use? The plugin doesn't need to have been implemented yet, just a concept if you had one. How do you envision people using the plugin feature in their workflow?

**Comment by TimUntersberger** [comment]
@keepitsane 

A few ideas:

- cp usages as components (needs a better stdlib)
- spotify current song playing component
- twitch viewer count component

**Comment by TimUntersberger** [comment]
Closing this issue since it is outdated.
