### ISSUE TITLE
Documentation links not working correctly on certain pages

### ISSUE THREAD

**Issue by errv01d** [TimUntersberger/nog#246]
In some pages of the documentation, text links to other pages don't navigate to the location they indicate.

In these instances, they appear to reload the current page.
A link in the sidebar to the relevant page *does* navigate correctly though.

Opening this issue to work on, as suggested in below thread comment by @TimUntersberger in https://github.com/TimUntersberger/nog/issues/242#issuecomment-784049426_

**Comment by errv01d** [comment]
Attached a list of currently broken links.
[Nog-Documentation-Broken_Links.txt](https://github.com/TimUntersberger/nog/files/6068497/Nog-Documentation-Broken_Links.txt)

It seems in all cases where a page _does_ exist, the sidebar link is correct/unaffected,
but the content pages themselves refer to their parent page only/contain empty links (`href=""`).

Eg. 'nog/docs/api/nog/config.html' - Empty links in document are generated for sub-entries (lines 173-178).

-----

@TimUntersberger
Hope you don't mind my question / apologies if it should be obvious - just to clarify though, is my understanding below correct?

1. The '/nog/doc-gen/src/main.rs' file is responsible for generating the .html/output files
2. It does this by parsing the markdown files located in '/nog/book/src'
3. In which case, I should concentrate on updating links in the .md files located under '/nog/book/src' ?

Appreciate your input on the above whenever you've got time - I'll keep looking over things until then to try and improve my understanding.


I'll start making changes on my fork under a new branch once confirmed that I'd be changing the right files/approaching the problem correctly

- Unless there's another/preferred way for me to contribute for this documentation fix/issue,
  - then please let me know and I'll do so as requested.


Kind Regards,
errv01d

**Comment by errv01d** [comment]
_Most_ changes made from attached list.
- Fork: errv01d
- Branch: iss246-documentation_links

Will look further into the below before considering submitting pull request.

Links added/changed that I'm unsure of...
- [configuration/settings.md](book/src/configuration/settings.md)
    - '**Scripting section**' should link somewhere other than '[api/nog.md](book/src/api/nog.md)'
    - '**Work mode**' should link somewhere other than '[api/nog/toggle_work_mode.md](book/src/api/nog/toggle_work_mode.md)'
- [configuration/modes.md](book/src/configuration/modes.md)
    - '**nog.enter_mode**' / '**nog.leave_mode**' functions differ from '[nog.toggle_mode](book/src/api/nog/toggle_mode.md)'
        - In which case, text/links to be reverted once pages exist
- [configuration/rules.md](book/src/configuration/rules.md)
    - '**../api/nog/window/match.md**' doesn't currently exist / not linked to
- [configuration/bar.md](book/src/configuration/bar.md)
    - A separate sub-section / '**../api/nog/bar/components.md**' should be created?
        - Possibly not due to last line advising to look at API reference for more info...
    - '**time**' / '**date**' / '**padding**' pages don't currently exist (?) / not linked to
    - '**workspaces**' / '**current_window**' / '**split_direction**' / '**current_mode**' pages should be linked to appropriate sections
        -  Pages should be created if they don't exist

**Comment by TimUntersberger** [comment]
Just to make sure: 

You do know that all `api` documentation is automatically generated using `doc-gen` right? Don't want you to waste a lot of time fixing the generated files. Fixing the api documentation part should be easy as you just have to correctly generate the path in the `main.rs` file.

**Comment by ramirezmike** [comment]
@TimUntersberger we should add a short instruction on how contributors can update the docs somewhere like maybe even the README.md or somewhere in the docs themselves. I also had trouble figuring it out.

**Comment by TimUntersberger** [comment]
I think this should be fixed since the rewrite of the documentation.
