### ISSUE TITLE
Document (how to discover) which key names are valid arguments to nog.bind()

### ISSUE THREAD

**Issue by garymm** [TimUntersberger/nog#260]
Thanks for this tool!

**Version (which release did you use?)**

02bfe58

**Describe the bug**

I have no clue how to discover the valid arguments for `nog.bind` or `nog.bind_map`.
Specifically I'm a new user and I'm trying to write a config.ns and I'm not sure how to bind something to the semicolon key.
I tried typing in ";", but that seems to just crash nog (which may be a separate bug?).

**Comment by garymm** [comment]
After poking around it seems like the answer is "the string form of the values of the [Key enum](https://github.com/TimUntersberger/nog/blob/master/twm/src/keybindings/key.rs)"

And to figure out the virtual key codes for a given keyboard, I was able to use [KeyboardStateView](https://www.nirsoft.net/utils/keyboard_state_view.html).

If maintainers can confirm this is correct, I can add this information to the documentation.
Would it go in [bind.md](https://github.com/TimUntersberger/nog/blob/master/book/src/api/nog/bind.md)?

**Comment by TimUntersberger** [comment]
This should be fixed once #259 is merged. Closing for now.
