### ISSUE TITLE
Set limit for current_window bar component length

### ISSUE THREAD

**Issue by keepitsane** [TimUntersberger/nog#275]
I was wondering if it is possible to limit the length of the current_window component. Occasionally when I have a browser tab with a long title it overlaps over the other components I have on my bar. 

Here is a picture to show:
![image](https://user-images.githubusercontent.com/13246774/122788174-11bc4800-d284-11eb-874f-895ac290a3e7.png)

What it normally looks like with a short title:
![image](https://user-images.githubusercontent.com/13246774/122788244-226cbe00-d284-11eb-808d-4cf3c340095f.png)

**Comment by TimUntersberger** [comment]
I think the current window component should just be cut off instead of overlapping other components in such a case.

**Comment by keepitsane** [comment]
Here is my config for my bar. Am I doing something incorrect to get it cutoff?

```lua
nog.config.bar.components = {
  left = {nog.components.workspaces()},
  center = {nog.components.datetime("%I:%M:%S %p")},
  right = {
    nog.components.active_mode(),
    nog.components.padding(4),
    nog.components.fullscreen_indicator("[]"),
    nog.components.padding(1),
    nog.components.split_direction({"|", "-"}),
    nog.components.padding(1),
    nog.components.current_window(),
    nog.components.padding(3),
    nog.components.datetime("%a, %e %b %Y")
  }
}
```

**Comment by TimUntersberger** [comment]
> I think the current window component should just be cut off instead of overlapping other components in such a case.

This was intended as a "we should change it to this behaviour"

**Comment by keepitsane** [comment]
The current_window() component used to only display on the workspace that the window is active on. But it seems now that the current_window() displays that same across all workspaces even on different monitors. I feel like it should really only show on the monitor that has the window rather than all. What do you think?

**Comment by TimUntersberger** [comment]
@keepitsane this should actually not be happening in the latest version. Do you have the latest version?

**Comment by keepitsane** [comment]
I just updated to the latest master version and am still experiencing both issues.

**Comment by ramirezmike** [comment]
I'm curious, when you installed it did you also replace the lua runtime in your appdata folder?

**Comment by keepitsane** [comment]
> 
> 
> I'm curious, when you installed it did you also replace the lua runtime in your appdata folder?

That was the issue. I assumed the nog.exe would auto replace the runtime as well, like the bin. But this did fix that issue, thank you!

**Comment by ramirezmike** [comment]
> > I'm curious, when you installed it did you also replace the lua runtime in your appdata folder?
> 
> That was the issue. I assumed the nog.exe would auto replace the runtime as well, like the bin. But this did fix that issue, thank you!

@TimUntersberger this might be something we might want to document or automate? As we make changes to the lua runtime it might not be obvious that the nog.exe and the runtime need to be replaced.

**Comment by TimUntersberger** [comment]
Maybe an "How to update" subsection in the getting started section.

**Comment by TimUntersberger** [comment]
The more I think about it the harder this seems to be 🤔 Maybe just using your initial idea of a max width is better.

**Comment by TimUntersberger** [comment]
Newest version now supports a max_width argument for the current_window component.

**Comment by TimUntersberger** [comment]
> I assumed the nog.exe would auto replace the runtime as well, like the bin. But this did fix that issue, thank you!

Running the following line **_should_** update everything.

`(iwr "https://raw.githubusercontent.com/TimUntersberger/nog/master/bin/download_release.ps1").Content > download.ps1; ./download.ps1 master-release; rm download.ps1`
