### ISSUE TITLE
creating window on one of Windows virtual desktop affects the workspace layout on another virtual desktop

### ISSUE THREAD

**Issue by TTTPOB** [TimUntersberger/nog#286]
**Version (which release did you use?)**

**Describe the bug**

creating window on one of Windows virtual desktop affects the workspace layout on another virtual desktop

**To Reproduce**

1. Create more than one virtual desktop
2. Create a workspace and open a window
3. Switch to the other virtual desktop
4. Create another window
5. You see the window on virtual desktop A and virtual desktop B are both half of the screen

**Expected behavior**

Workspaces maintain dependent on difference virutal desktops

**Actual behavior**

creating window on one of Windows virtual desktop affects the workspace layout on another virtual desktop

**Comment by TimUntersberger** [comment]
Is there a reason why you are using virtual desktops together with a window manager?

AFAIK there should be no reason to use them together, so right now we aren't planning on supporting virtual desktops.

**Comment by TTTPOB** [comment]
after a second thought I think you are right, why should I use virtual desktop along with nog...
