### ISSUE TITLE
Rotating/Switching tiles within a workspace

### ISSUE THREAD

**Issue by ramirezmike** [TimUntersberger/nog#94]
A feature should be added that allows you to "swap" the splits in the current workspace. 

If a user has three tiles displaying as columns, each taking up a third of the width of the screen, this feature would allow them to "rotate" the tiles so they appear as three row'd tiles each taking up a third of the height of the screen.

**Comment by TimUntersberger** [comment]
Requires #93

**Comment by ramirezmike** [comment]
Implemented in #193
